// Package definition parses the ordered instructions in a Coopr definition.
package definition

import (
	"fmt"
	"io"
	"maps"
	"math"
	"math/big"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"time"

	kdl "github.com/calico32/kdl-go"
)

// Definition is the parsed, unevaluated instruction sequence.
type Definition struct {
	Instructions []Instruction `json:"instructions"`
}

// Instruction retains its source order and string values for later planning.
type Instruction struct {
	// LayerBoundary marks an internal ordered group boundary after planning.
	// Public definitions retain nested layer instructions instead.
	LayerBoundary string            `json:"layer_boundary,omitempty"`
	Name          string            `json:"name"`
	Form          string            `json:"form,omitempty"`
	Arguments     []string          `json:"arguments,omitempty"`
	Properties    map[string]string `json:"properties,omitempty"`
	Children      []Instruction     `json:"children,omitempty"`
	InlineFiles   []InlineFile      `json:"inline_files,omitempty"`
	// ProcessQuotes marks Dockerfile words imported from ONBUILD metadata.
	// The planner processes their Docker quoting and expansion together in the
	// child stage, then clears this internal marker from the normalized result.
	ProcessQuotes bool `json:"process_quotes,omitempty"`
	// DeferredOnBuild retains an imported RUN trigger until child-stage scope
	// exists. It is consumed by planning, never exposed as authored syntax.
	DeferredOnBuild string `json:"deferred_onbuild,omitempty"`
}

// InlineFile is a Dockerfile heredoc source retained through planning.
type InlineFile struct {
	Path   string `json:"path"`
	Data   string `json:"data"`
	Expand bool   `json:"expand,omitempty"`
}

// Validate checks an already decoded definition using the same instruction
// rules as Parse. Publication metadata is decoded from JSON, so it must not
// bypass these checks before planning.
func Validate(def *Definition) error {
	if def == nil || len(def.Instructions) == 0 {
		return fmt.Errorf("empty Coopr definition")
	}
	for i, inst := range def.Instructions {
		if err := rejectLayerBoundaries(inst); err != nil {
			return fmt.Errorf("instruction %d: %w", i+1, err)
		}
		if err := validateInstruction(inst, fmt.Sprintf("instruction %d", i+1), false, false); err != nil {
			return err
		}
	}
	return nil
}

// Group boundaries are generated by FlattenLayers, never authored or trusted
// from publication metadata. Rejecting them also prevents unbalanced groups.
func rejectLayerBoundaries(inst Instruction) error {
	if inst.LayerBoundary != "" {
		return fmt.Errorf("layer boundaries are internal; use a layer block")
	}
	for _, child := range inst.Children {
		if err := rejectLayerBoundaries(child); err != nil {
			return err
		}
	}
	return nil
}

// ValidateResolved checks an instruction after argument substitution. Call it
// on instructions selected for execution; deferred component instructions are
// checked when their invocation arguments become available.
func ValidateResolved(inst Instruction) error {
	return validateInstruction(inst, "resolved instruction", false, true)
}

func validateInstruction(inst Instruction, position string, child, resolved bool) error {
	if child && inst.Name != "mount" && inst.Name != "device" && inst.Name != "exclude" {
		return fmt.Errorf("%s: unsupported child %q", position, inst.Name)
	}
	if err := validate(inst, len(inst.Children), child, resolved); err != nil {
		return fmt.Errorf("%s %q: %w", position, inst.Name, err)
	}
	for i, nested := range inst.Children {
		if inst.Name == "layer" {
			if nested.Name == "from" || nested.Name == "extend" || nested.Name == "package" {
				return fmt.Errorf("%s: stage declarations are not allowed inside layer", position)
			}
			if err := validateInstruction(nested, fmt.Sprintf("%s layer child %d", position, i+1), false, resolved); err != nil {
				return err
			}
			continue
		}
		if inst.Name == "extend" {
			if err := validateExtendRequirement(nested); err != nil {
				return fmt.Errorf("%s %q child %d: %w", position, inst.Name, i+1, err)
			}
			continue
		}
		if (nested.Name == "mount" || nested.Name == "device") && inst.Name != "run" {
			return fmt.Errorf("%s %q child %d: %s children require run", position, inst.Name, i+1, nested.Name)
		}
		if nested.Name == "exclude" && inst.Name != "copy" && inst.Name != "add" {
			return fmt.Errorf("%s %q child %d: exclude children require copy or add", position, inst.Name, i+1)
		}
		if err := validateInstruction(nested, fmt.Sprintf("%s %q child %d", position, inst.Name, i+1), true, resolved); err != nil {
			return err
		}
	}
	return nil
}

// Parse reads a KDL v2 Coopr definition and validates individual instructions.
// References, argument expansion, and phase dependencies are planner concerns.
func Parse(r io.Reader) (*Definition, error) {
	source, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("read Coopr definition: %w", err)
	}
	doc, err := kdl.ParseString(string(source), kdl.WithVersion(kdl.Version2))
	if err != nil {
		return nil, fmt.Errorf("parse KDL v2: %w", err)
	}
	if len(doc.Nodes) == 0 {
		return nil, fmt.Errorf("empty Coopr definition")
	}
	def := &Definition{Instructions: make([]Instruction, 0, len(doc.Nodes))}
	for i, node := range doc.Nodes {
		inst, err := parseNode(node, source, fmt.Sprintf("instruction %d", i+1), false)
		if err != nil {
			return nil, err
		}
		def.Instructions = append(def.Instructions, inst)
	}
	return def, nil
}

func parseNode(node *kdl.Node, source []byte, position string, child bool) (Instruction, error) {
	position = fmt.Sprintf("%s at %s", position, node.Location())
	inst := Instruction{Name: node.Name()}
	if child && inst.Name != "mount" && inst.Name != "device" && inst.Name != "exclude" {
		return inst, fmt.Errorf("%s: unsupported child %q", position, inst.Name)
	}
	if err := validateInstructionName(inst.Name); err != nil {
		return inst, fmt.Errorf("%s: %w", position, err)
	}
	healthcheckDisabled := false
	command := inst.Name == "run" || inst.Name == "cmd" || inst.Name == "entrypoint" || inst.Name == "healthcheck"
	if _, annotated := node.TypeAnnotation(); annotated {
		return inst, fmt.Errorf("%s %q: annotations are not supported", position, inst.Name)
	}
	arguments := node.Arguments()
	for i, nested := range node.Children().Nodes {
		if nested.Name() != "exec" {
			continue
		}
		if !command {
			return inst, fmt.Errorf("%s %q child %d: exec requires run, cmd, entrypoint, or healthcheck", position, inst.Name, i+1)
		}
		if len(node.Arguments()) != 0 {
			return inst, fmt.Errorf("%s %q: cannot combine shell text and an exec child", position, inst.Name)
		}
		if inst.Form == "exec" {
			return inst, fmt.Errorf("%s %q: expected exactly one exec child", position, inst.Name)
		}
		if _, annotated := nested.TypeAnnotation(); annotated {
			return inst, fmt.Errorf("%s %q child %d: annotations are not supported", position, inst.Name, i+1)
		}
		if len(nested.Properties()) != 0 || len(nested.Children().Nodes) != 0 {
			return inst, fmt.Errorf("%s %q child %d: exec accepts arguments only", position, inst.Name, i+1)
		}
		inst.Form = "exec"
		arguments = nested.Arguments()
	}
	for i, value := range arguments {
		if _, annotated := value.TypeAnnotation(); annotated {
			return inst, fmt.Errorf("%s %q: argument %d annotations are not supported", position, inst.Name, i+1)
		}
		// Bare NONE disables a healthcheck; quoted NONE remains a command.
		// The AST retains spans, but Literal omits ordinary quoted strings.
		if inst.Name == "healthcheck" && inst.Form != "exec" && value.Kind() == kdl.String && value.String() == "NONE" && string(source[value.Location().Offset:value.EndLocation().Offset]) == "NONE" {
			if len(arguments) != 1 {
				return inst, fmt.Errorf("%s %q: NONE must be the only argument", position, inst.Name)
			}
			healthcheckDisabled = true
			inst.Arguments = []string{"NONE"}
			continue
		}
		s, err := normalizeScalar(value, false)
		if err != nil {
			return inst, fmt.Errorf("%s %q: argument %d %w", position, inst.Name, i+1, err)
		}
		inst.Arguments = append(inst.Arguments, s)
	}
	nodeProperties := node.Properties()
	for _, name := range slices.Sorted(maps.Keys(nodeProperties)) {
		value := nodeProperties[name]
		if command && (name == "shell" || name == "form") {
			return inst, fmt.Errorf("%s %q: %s property is not supported; use shell text or an exec child", position, inst.Name, name)
		}
		permission := (inst.Name == "copy" || inst.Name == "add") && name == "chmod" || inst.Name == "mount" && (name == "mode" || name == "tmpfs-mode")
		s, err := normalizeScalar(value, permission)
		if err != nil {
			return inst, fmt.Errorf("%s %q: property %q %w", position, inst.Name, name, err)
		}
		if inst.Properties == nil {
			inst.Properties = make(map[string]string, len(nodeProperties))
		}
		inst.Properties[name] = s
	}
	applyCommandDefaults(&inst, healthcheckDisabled)
	if healthcheckDisabled && (inst.Form != "" || len(inst.Properties) != 0) {
		return inst, fmt.Errorf("%s %q: NONE does not accept properties", position, inst.Name)
	}
	if inst.Name == "healthcheck" && !healthcheckDisabled && (len(inst.Arguments) > 0 || inst.Form == "exec") {
		if inst.Form == "exec" {
			inst.Arguments = append([]string{"CMD"}, inst.Arguments...)
		} else {
			inst.Arguments = append([]string{"CMD-SHELL"}, inst.Arguments...)
		}
		inst.Form = ""
	}
	if inst.Name == "run" && inst.Form == "shell" && len(node.Arguments()) == 1 && strings.HasPrefix(inst.Arguments[0], "#!") {
		literal, _ := node.Arguments()[0].Literal()
		if strings.HasPrefix(strings.TrimLeft(literal, "#"), `"""`) {
			inst.Form = "exec"
			inst.InlineFiles = []InlineFile{{Path: "script", Data: inst.Arguments[0]}}
			inst.Arguments = []string{"/run/coopr-heredoc/script"}
		}
	}
	if inst.Name == "onbuild" {
		if len(node.Arguments()) != 0 || len(nodeProperties) != 0 {
			return inst, fmt.Errorf("%s %q: expected no arguments or properties and exactly one child", position, inst.Name)
		}
		if len(node.Children().Nodes) != 1 {
			return inst, fmt.Errorf("%s %q: expected exactly one child", position, inst.Name)
		}
		triggerInstruction, err := parseNode(node.Children().Nodes[0], source, position+` "onbuild" child 1`, false)
		if err != nil {
			return inst, err
		}
		trigger, err := formatOnBuild(triggerInstruction)
		if err != nil {
			return inst, fmt.Errorf("%s %q: %w", position, inst.Name, err)
		}
		inst.Arguments = []string{trigger}
		if err := validate(inst, 0, child, false); err != nil {
			return inst, fmt.Errorf("%s %q: %w", position, inst.Name, err)
		}
		return inst, nil
	}
	if len(node.Children().Nodes) > 0 && (child || (!command && inst.Name != "copy" && inst.Name != "add" && inst.Name != "extend" && inst.Name != "layer")) {
		return inst, fmt.Errorf("%s %q: children are only allowed on command, copy, add, extend, layer, or onbuild instructions", position, inst.Name)
	}
	for i, childNode := range node.Children().Nodes {
		if childNode.Name() == "exec" {
			continue
		}
		if inst.Name == "extend" {
			requirement, err := parseExtendRequirement(childNode)
			if err != nil {
				return inst, fmt.Errorf("%s %q child %d at %s: %w", position, inst.Name, i+1, childNode.Location(), err)
			}
			inst.Children = append(inst.Children, requirement)
			continue
		}
		nested, err := parseNode(childNode, source, fmt.Sprintf("%s %q child %d", position, inst.Name, i+1), inst.Name != "layer")
		if err != nil {
			return inst, err
		}
		if (nested.Name == "mount" || nested.Name == "device") && inst.Name != "run" {
			return inst, fmt.Errorf("%s %q child %d: %s children require run", position, inst.Name, i+1, nested.Name)
		}
		if nested.Name == "exclude" && inst.Name != "copy" && inst.Name != "add" {
			return inst, fmt.Errorf("%s %q child %d: exclude children require copy or add", position, inst.Name, i+1)
		}
		if inst.Name == "layer" && (nested.Name == "from" || nested.Name == "extend" || nested.Name == "package") {
			return inst, fmt.Errorf("%s: stage declarations are not allowed inside layer", position)
		}
		inst.Children = append(inst.Children, nested)
	}
	if err := validate(inst, len(inst.Children), child, false); err != nil {
		return inst, fmt.Errorf("%s %q: %w", position, inst.Name, err)
	}
	return inst, nil
}

func parseExtendRequirement(node *kdl.Node) (Instruction, error) {
	requirement := Instruction{Name: node.Name()}
	if _, annotated := node.TypeAnnotation(); annotated {
		return requirement, fmt.Errorf("annotations are not supported")
	}
	for i, value := range node.Arguments() {
		if _, annotated := value.TypeAnnotation(); annotated {
			return requirement, fmt.Errorf("argument %d annotations are not supported", i+1)
		}
		if value.Kind() != kdl.String {
			return requirement, fmt.Errorf("argument %d must be a string", i+1)
		}
		requirement.Arguments = append(requirement.Arguments, value.String())
	}
	if len(node.Properties()) != 0 || len(node.Children().Nodes) != 0 {
		return requirement, fmt.Errorf("compatibility requirement must contain only string values")
	}
	if err := validateExtendRequirement(requirement); err != nil {
		return requirement, err
	}
	return requirement, nil
}

func validateExtendRequirement(requirement Instruction) error {
	if requirement.Form != "" || len(requirement.Properties) != 0 || len(requirement.Children) != 0 || len(requirement.InlineFiles) != 0 {
		return fmt.Errorf("compatibility requirement must contain only string values")
	}
	switch requirement.Name {
	case "architecture", "distro", "distro-version", "package-manager":
	default:
		return fmt.Errorf("unknown compatibility requirement %q", requirement.Name)
	}
	if len(requirement.Arguments) == 0 {
		return fmt.Errorf("compatibility requirement %q needs at least one value", requirement.Name)
	}
	return nil
}

func applyCommandDefaults(inst *Instruction, healthcheckDisabled bool) {
	switch inst.Name {
	case "run", "cmd", "entrypoint":
		if inst.Form == "" {
			inst.Form = "shell"
			if inst.Name != "run" && len(inst.Arguments) == 0 {
				inst.Form = "exec"
			}
		}
	case "healthcheck":
		if len(inst.Arguments) > 0 && !healthcheckDisabled && inst.Form == "" {
			inst.Form = "shell"
		}
	}
}

func normalizeScalar(value kdl.Value, permission bool) (string, error) {
	if _, annotated := value.TypeAnnotation(); annotated {
		return "", fmt.Errorf("annotations are not supported")
	}
	literal, _ := value.Literal()
	octalPermission := permission && strings.HasPrefix(literal, "0o")
	switch resolved := value.RawValue().(type) {
	case nil:
		return "", fmt.Errorf("null is not supported")
	case string:
		return resolved, nil
	case bool:
		return strconv.FormatBool(resolved), nil
	case int:
		if octalPermission {
			return fmt.Sprintf("%#o", resolved), nil
		}
		return strconv.Itoa(resolved), nil
	case float64:
		if math.IsInf(resolved, 0) || math.IsNaN(resolved) {
			return "", fmt.Errorf("must be a finite number")
		}
		return strconv.FormatFloat(resolved, 'g', -1, 64), nil
	case *big.Int:
		if octalPermission {
			return fmt.Sprintf("%#o", resolved), nil
		}
		return resolved.String(), nil
	case *big.Float:
		if resolved.IsInf() {
			return "", fmt.Errorf("must be a finite number")
		}
		return resolved.Text('g', -1), nil
	default:
		return "", fmt.Errorf("must be a string, boolean, or finite number")
	}
}

func validate(inst Instruction, childCount int, child, resolved bool) error {
	if err := validateInstructionName(inst.Name); err != nil {
		return err
	}
	if names, fixed := InstructionProperties(inst.Name); fixed {
		if inst.Name == "run" {
			if _, hidden := inst.Properties["mount"]; hidden {
				return fmt.Errorf("use a mount child for mount options")
			}
		}
		if err := ValidateProperties(inst.Properties, names...); err != nil {
			return err
		}
	}
	n, p, a := inst.Name, inst.Properties, len(inst.Arguments)
	if len(inst.InlineFiles) != 0 && n != "run" && n != "copy" && n != "add" {
		return fmt.Errorf("inline files are only allowed on run, copy, or add")
	}
	for _, file := range inst.InlineFiles {
		if file.Path == "" || !filepath.IsLocal(filepath.FromSlash(file.Path)) || file.Path == "." || strings.ContainsRune(file.Path, '\x00') || strings.ContainsRune(file.Data, '\x00') {
			return fmt.Errorf("inline file path and data must be nonempty-path, NUL-free strings")
		}
	}
	if inst.Form != "" && inst.Form != "exec" && inst.Form != "shell" {
		return fmt.Errorf("unknown instruction form %q", inst.Form)
	}
	if inst.Form != "" && n != "run" && n != "cmd" && n != "entrypoint" {
		return fmt.Errorf("instruction form is only allowed on run, cmd, or entrypoint")
	}
	if childCount > 0 && (child || (n != "run" && n != "copy" && n != "add" && n != "extend" && n != "layer")) {
		return fmt.Errorf("children are only allowed on run, copy, add, extend, or layer instructions")
	}
	if inst.LayerBoundary != "" && (n != "layer" || childCount != 0 || inst.LayerBoundary != "begin" && inst.LayerBoundary != "end") {
		return fmt.Errorf("invalid layer boundary")
	}
	switch n {
	case "layer":
		if a != 0 || len(p) != 0 {
			return fmt.Errorf("layer accepts no arguments or properties")
		}
	case "exec":
		return fmt.Errorf("exec must be a child of run, cmd, entrypoint, or healthcheck")
	case "from":
		if a != 1 {
			return fmt.Errorf("expected one source and optional as/platform/after properties")
		}
	case "extend":
		if a != 0 {
			return fmt.Errorf("expected no arguments and optional as/distro/distro-version/package-manager/architecture properties")
		}
		declared := make(map[string]bool, len(inst.Children))
		for _, requirement := range inst.Children {
			if err := validateExtendRequirement(requirement); err != nil {
				return err
			}
			_, scalar := p[requirement.Name]
			if declared[requirement.Name] || scalar {
				return fmt.Errorf("duplicate compatibility requirement %q", requirement.Name)
			}
			declared[requirement.Name] = true
		}
		_, versionProperty := p["distro-version"]
		_, distroProperty := p["distro"]
		if (versionProperty || declared["distro-version"]) && !distroProperty && !declared["distro"] {
			return fmt.Errorf("distro-version requires distro")
		}
	case "package":
		if a != 0 || strings.TrimSpace(p["as"]) == "" {
			return fmt.Errorf("expected no arguments and a nonempty as property")
		}
	case "arg":
		if (a != 1 && a != 2) || len(p) != 0 {
			return fmt.Errorf("expected a name, optional default, and no properties")
		}
	case "run":
		if err := validatePropertyEnum(p, "security", resolved, "sandbox", "insecure"); err != nil {
			return err
		}
		if a < 1 || (inst.Form != "exec" && a != 1) {
			return fmt.Errorf("expected one shell command or exec arguments")
		}
		if len(inst.InlineFiles) != 0 && (inst.Form != "exec" || a != 1 || len(inst.InlineFiles) != 1) {
			return fmt.Errorf("RUN inline executable requires one exec argument and one inline file")
		}
	case "copy", "add":
		if a < 1 || a-1+len(inst.InlineFiles) < 1 {
			return fmt.Errorf("expected source(s) and destination")
		}
		if _, ok := p["from"]; ok && strings.TrimSpace(p["from"]) == "" {
			return fmt.Errorf("from property cannot be empty")
		}
		if _, ok := p["chown"]; ok && strings.TrimSpace(p["chown"]) == "" {
			return fmt.Errorf("chown property cannot be empty")
		}
		if _, ok := p["chmod"]; ok && strings.TrimSpace(p["chmod"]) == "" {
			return fmt.Errorf("chmod property cannot be empty")
		}
	case "env", "label":
		if len(p) == 0 && a != 2 {
			return fmt.Errorf("expected properties or a key and value")
		}
		if len(p) > 0 && a != 0 {
			return fmt.Errorf("cannot mix arguments and properties")
		}
		if a == 2 && (inst.Arguments[0] == "" || strings.ContainsAny(inst.Arguments[0], "=\x00")) {
			return fmt.Errorf("expected a nonempty key without equals sign")
		}
		if n == "env" && a == 2 && strings.ContainsRune(inst.Arguments[1], '\x00') {
			return fmt.Errorf("environment value cannot contain NUL")
		}
		for _, key := range slices.Sorted(maps.Keys(p)) {
			if key == "" || strings.ContainsAny(key, "=\x00") {
				return fmt.Errorf("expected a nonempty key without equals sign")
			}
			if n == "env" && strings.ContainsRune(p[key], '\x00') {
				return fmt.Errorf("environment value cannot contain NUL")
			}
		}
	case "workdir", "user":
		if a != 1 || len(p) != 0 || strings.TrimSpace(inst.Arguments[0]) == "" {
			return fmt.Errorf("expected one nonempty argument and no properties")
		}
	case "cmd", "entrypoint":
		if len(p) != 0 || (inst.Form == "shell" && a != 1) {
			return fmt.Errorf("expected exec arguments (empty resets) or one shell command and no properties")
		}
	case "healthcheck":
		if err := validateHealthcheck(inst, resolved); err != nil {
			return err
		}
	case "onbuild":
		if a != 1 || len(p) != 0 || strings.TrimSpace(inst.Arguments[0]) == "" {
			return fmt.Errorf("expected one nonempty Dockerfile instruction and no properties")
		}
		if strings.ContainsRune(inst.Arguments[0], '\x00') {
			return fmt.Errorf("dockerfile instruction cannot contain NUL")
		}
	case "component":
		if a != 1 || strings.TrimSpace(inst.Arguments[0]) == "" || childCount != 0 {
			return fmt.Errorf("expected one component reference, argument properties, and no children")
		}
	case "mount":
		if !child || a != 1 || inst.Arguments[0] == "" || childCount != 0 {
			return fmt.Errorf("expected a mount type and optional properties, and no children")
		}
		if err := validateMountProperties(inst.Arguments[0], p, resolved); err != nil {
			return err
		}
	case "device":
		if !child || a < 1 || childCount != 0 {
			return fmt.Errorf("expected one or more device selectors, optional required property, and no children")
		}
		for _, selector := range inst.Arguments {
			if strings.TrimSpace(selector) == "" {
				return fmt.Errorf("device selector cannot be empty")
			}
		}
		if required, ok := p["required"]; ok && (resolved || !strings.Contains(required, "$")) {
			if required != "true" && required != "false" {
				return fmt.Errorf("required property must be a boolean")
			}
		}
	case "exclude":
		if !child || a < 1 || len(p) != 0 || childCount != 0 {
			return fmt.Errorf("expected one or more exclude patterns and no properties or children")
		}
	case "shell", "expose", "volume":
		if a == 0 {
			return fmt.Errorf("expected at least one argument and no properties")
		}
	case "stopsignal", "maintainer":
		if a != 1 || strings.TrimSpace(inst.Arguments[0]) == "" {
			return fmt.Errorf("expected one nonempty argument and no properties")
		}

	}
	return nil
}

func validateHealthcheck(inst Instruction, resolved bool) error {
	if len(inst.Arguments) == 0 {
		return fmt.Errorf("expected CMD, CMD-SHELL, or NONE")
	}
	for _, argument := range inst.Arguments {
		if strings.ContainsRune(argument, '\x00') {
			return fmt.Errorf("healthcheck arguments cannot contain NUL")
		}
	}
	switch inst.Arguments[0] {
	case "NONE":
		if len(inst.Arguments) != 1 {
			return fmt.Errorf("NONE does not accept command arguments")
		}
		if len(inst.Properties) != 0 {
			return fmt.Errorf("NONE does not accept properties")
		}
		return nil
	case "CMD":
		if len(inst.Arguments) < 2 {
			return fmt.Errorf("CMD requires at least one command argument")
		}
	case "CMD-SHELL":
		if len(inst.Arguments) != 2 {
			return fmt.Errorf("CMD-SHELL requires exactly one command")
		}
	default:
		return fmt.Errorf("expected CMD, CMD-SHELL, or NONE")
	}

	for _, name := range []string{"interval", "timeout", "start-period", "start-interval"} {
		value, exists := inst.Properties[name]
		if !exists || (!resolved && strings.Contains(value, "$")) {
			continue
		}
		duration, err := time.ParseDuration(value)
		if err != nil {
			return fmt.Errorf("%s property must be a duration: %w", name, err)
		}
		if duration != 0 && duration < time.Millisecond {
			return fmt.Errorf("%s property cannot be less than 1ms", name)
		}
	}
	if value, exists := inst.Properties["retries"]; exists && (resolved || !strings.Contains(value, "$")) {
		retries, err := strconv.Atoi(value)
		if err != nil || retries < 0 {
			return fmt.Errorf("retries property must be a nonnegative integer")
		}
	}
	return nil
}

// FlattenLayers exposes group children to the ordinary ordered planner while
// retaining internal begin/end markers for execution. Parse and Validate keep
// public definitions nested and prohibit authored boundaries.
func FlattenLayers(instructions []Instruction) []Instruction {
	var result []Instruction
	for _, inst := range instructions {
		if inst.Name != "layer" || inst.LayerBoundary != "" {
			result = append(result, inst)
			continue
		}
		result = append(result, Instruction{Name: "layer", LayerBoundary: "begin"})
		result = append(result, FlattenLayers(inst.Children)...)
		result = append(result, Instruction{Name: "layer", LayerBoundary: "end"})
	}
	return result
}
