package buildah

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"

	"coopr/internal/planner"
	"github.com/containerd/platforms"
	"github.com/opencontainers/go-digest"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
)

// CacheMountScope binds an autogenerated RUN cache ID to immutable source
// content. A component's source is the selected OCI manifest digest, which
// also binds its package descriptors and metadata.
type CacheMountScope struct {
	Kind       string
	Source     digest.Digest
	Platform   v1.Platform
	Parameters map[string]string
	Stage      string
}

// graphCacheMountIDResolver scopes a root definition to the executable plan.
// Component calls use scopedCacheMountIDResolver with the artifact digest.
func graphCacheMountIDResolver(plan *planner.Plan, stage planner.Stage) (CacheMountIDResolver, error) {
	scope, err := graphCacheMountScope(plan, stage)
	if err != nil {
		return nil, err
	}
	return scopedCacheMountIDResolver(scope)
}

func graphCacheMountScope(plan *planner.Plan, stage planner.Stage) (CacheMountScope, error) {
	if plan == nil {
		return CacheMountScope{}, fmt.Errorf("cache mount plan is nil")
	}
	encoded, err := json.Marshal(plan)
	if err != nil {
		return CacheMountScope{}, fmt.Errorf("encode definition cache mount source: %w", err)
	}
	platform, err := platforms.Parse(plan.Platform)
	if err != nil {
		return CacheMountScope{}, fmt.Errorf("parse cache mount platform: %w", err)
	}
	return CacheMountScope{
		Kind: "definition", Source: digest.FromBytes(encoded), Platform: platform, Stage: stage.ID,
	}, nil
}

// scopedCacheMountIDResolver gives an omitted cache ID a deterministic scope.
// The target separates independent caches, while explicit IDs bypass this
// namespace and retain Buildah's normal sharing behavior.
func scopedCacheMountIDResolver(scope CacheMountScope) (CacheMountIDResolver, error) {
	if scope.Kind != "definition" && scope.Kind != "component" {
		return nil, fmt.Errorf("invalid cache mount scope kind %q", scope.Kind)
	}
	if scope.Source.Algorithm() != digest.SHA256 || scope.Source.Validate() != nil {
		return nil, fmt.Errorf("invalid cache mount source digest %q", scope.Source)
	}
	if scope.Stage == "" || scope.Platform.OS != "linux" || scope.Platform.Architecture == "" {
		return nil, fmt.Errorf("cache mount scope requires a stage and Linux platform")
	}
	parameters, err := planner.NormalizeParameters(scope.Parameters)
	if err != nil {
		return nil, err
	}
	identity := struct {
		Version, Kind string
		Source        digest.Digest
		Platform      v1.Platform
		Parameters    json.RawMessage
		Stage         string
	}{"coopr.buildah-cache-mount.v1", scope.Kind, scope.Source, platforms.Normalize(scope.Platform), parameters, scope.Stage}
	encoded, err := json.Marshal(identity)
	if err != nil {
		return nil, fmt.Errorf("encode cache mount scope: %w", err)
	}
	scopeSum := sha256.Sum256(encoded)
	return func(operation planner.Operation, mountIndex int) (string, error) {
		if mountIndex < 0 || mountIndex >= len(operation.Children) {
			return "", fmt.Errorf("cache mount index %d is outside RUN children", mountIndex)
		}
		mount := operation.Children[mountIndex]
		if mount.Name != "mount" || len(mount.Arguments) != 1 || mount.Arguments[0] != "cache" {
			return "", fmt.Errorf("RUN child %d is not a cache mount", mountIndex+1)
		}
		target := mount.Properties["target"]
		if target == "" {
			return "", fmt.Errorf("cache mount target is empty")
		}
		sharing := mount.Properties["sharing"]
		if sharing == "" {
			sharing = "shared"
		}
		physical := sha256.Sum256([]byte(fmt.Sprintf("%x\x00%s\x00%s", scopeSum, target, sharing)))
		return fmt.Sprintf("coopr-%x", physical), nil
	}, nil
}
